version: '2'

services:
  todo_list:
    build: ./
    image: todolist:latest
    container_name: todo_list
    restart: always
    environment:
      MYSQL_DSN: "root:!@#qwe123@tcp(mysql:3306)/todolist_db?charset=utf8&parseTime=True&loc=Local"
    ports:
        - 3000:3000
    depends_on:
      - mysql
      - redis

  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '!@#qwe123'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_DATABASE: 'todolist_db'
    volumes:
      - /root/todolist_volumes/local/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password #解决mysql外部无法访问的问题

  redis:
    container_name: redis
    image: redis:4.0.14
    restart: always
    privileged: true
    volumes:
      - /root/todolist_volumes/local/redis:/var/lib/redis

    ports:
      - 6379:6379
